services:
  presentation-service:
    container_name: WebApi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8085:8085"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    volumes:
      - ./Presentation:/src/Presentation
      - ./DataLayer:/src/DataLayer
      - ./Models:/src/Models
      - ./ServiceLayer:/src/ServiceLayer
    depends_on:
      - sqlserver
    networks:
      - PeachCrate
    entrypoint: ["/app/wait-for-it.sh", "sqlserver-container:1433", "--", "dotnet", "Presentation.dll"]
        
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    networks:
      - PeachCrate
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  PeachCrate:
